#!/bin/bash
# 整合SocatSystem全部功能的hhminer管理脚本
# 原版hhminer + install.sh全功能复刻

# ===================== 基础常量定义 =====================
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[34m'
bold='\033[1m'
plain='\033[0m'

# hhminer基础路径（保留原版）
installPath=/opt/hhminer
updatePath=${installPath}/update
serviceName=hhminer
APP_ID="hhminer"
APP_NAME="hhMiner Proxy"
VERSION="5.0.0"
DOWNLOAD_HOST="https://raw.githubusercontent.com/735840086/hhminer/main"
CLI_EXEC_NAME="hhminerCLI-0.1.0"
CLI_COMMAND_NAME="hhminerctl"
CLI_LINK_PATH="/usr/local/bin/${CLI_COMMAND_NAME}"
CLI_LAUNCHER_MARKER="Generated by hhminer.sh install script"

# 配置文件与运行日志路径
CONFIG_FILE_NAME="rust-config"
PATH_CONFIG="${installPath}/${CONFIG_FILE_NAME}"
PATH_NOHUP="${installPath}/nohup.out"
PATH_ERR="${installPath}/err.log"
PATH_CUE="${installPath}/cue"
PATH_D_1="${installPath}/0.d1"
PATH_D_2="${installPath}/0.d1-shm"
PATH_D_3="${installPath}/0.d1-wal"
PATH_CLI="${installPath}/${CLI_EXEC_NAME}"
PATH_CLI_TMP="${installPath}/${CLI_EXEC_NAME}.tmp"
SYSCTL_TAG="${APP_ID}"

# 进程等待参数
PROCESS_WAIT_INTERVAL="0.1"
PROCESS_WAIT_STEPS_PER_SECOND=10
PROCESS_WAIT_INTERVAL_SUPPORTED=""

# ===================== 系统检测函数（原版保留） =====================
check_os() {
    if [[ -f /etc/redhat-release ]]; then
        os="centos"
    elif cat /etc/issue | grep -Eqi "debian"; then
        os="debian"
    elif cat /etc/issue | grep -Eqi "ubuntu"; then
        os="ubuntu"
    elif cat /proc/version | grep -Eqi "debian"; then
        os="debian"
    elif cat /proc/version | grep -Eqi "ubuntu"; then
        os="ubuntu"
    elif cat /proc/version | grep -Eqi "centos|red hat|redhat"; then
        os="centos"
    fi
}

# 获取公网IP（融合两个脚本最优逻辑）
get_ip(){
    local IP=""
    # 优先内网出口IP
    if command -v ip >/dev/null 2>&1; then
        IP=$(ip addr | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\." | head -n 1 )
    fi
    # 公网接口
    if [ -z "$IP" ] && command -v curl >/dev/null 2>&1; then
        IP=$(curl -fsSL --max-time 2 https://ipv4.icanhazip.com 2>/dev/null | tr -d '[:space:]')
    fi
    if [ -z "$IP" ] && command -v wget >/dev/null 2>&1; then
        IP=$(wget -qO- -t1 -T2 ipv4.icanhazip.com | tr -d '[:space:]')
    fi
    if [ -z "$IP" ] && command -v hostname >/dev/null 2>&1; then
        IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    fi
    [ -z ${IP} ] && IP=$( wget -qO- -t1 -T2 ipinfo.io/ip 2>/dev/null )
    [ ! -z ${IP} ] && echo ${IP} || echo "127.0.0.1"
}

# ===================== 权限/系统依赖检测 =====================
require_root() {
    [ "$(id -u)" != "0" ] && { echo -e "[${red}错误${plain}] 需要root权限执行脚本"; exit 1; }
}

is_systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}

detect_system() {
    OS_ID="unknown"
    OS_LIKE=""
    OS_NAME="$(uname -s)"
    INIT_SYSTEM="unknown"
    if [ -r /etc/os-release ]; then
        OS_ID=$(sh -c '. /etc/os-release; printf "%s" "${ID:-unknown}"')
        OS_LIKE=$(sh -c '. /etc/os-release; printf "%s" "${ID_LIKE:-}"')
        OS_NAME=$(sh -c '. /etc/os-release; printf "%s" "${PRETTY_NAME:-${ID:-unknown}}"')
    fi
    if is_systemd_available; then
        INIT_SYSTEM="systemd"
    elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then
        INIT_SYSTEM="openrc"
    elif command -v service >/dev/null 2>&1; then
        INIT_SYSTEM="sysv"
    fi
}

check_dependencies() {
    local missing=""
    local cmd
    for cmd in pgrep sed grep mkdir chmod touch tail awk find ip wget; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            missing="${missing} ${cmd}"
        fi
    done
    if [ -n "$missing" ]; then
        echo -e "[${red}错误${plain}] 缺失依赖命令:$missing"
        return 1
    fi
    if ! command -v wget >/dev/null 2>&1 && ! command -v curl >/dev/null 2>&1; then
        echo -e "[${red}错误${plain}] 缺少下载工具wget/curl"
        return 1
    fi
}

# ===================== 文件下载工具 =====================
download_file() {
    local url="$1"
    local output="$2"
    echo -e "[${yellow}下载${plain}] 源地址:$url"
    echo -e "[${yellow}下载${plain}] 保存路径:$output"
    if command -v wget >/dev/null 2>&1; then
        if wget --help 2>&1 | grep -q -- "--show-progress"; then
            wget --show-progress --progress=bar:force:noscroll "$url" -O "$output" --no-check-certificate
        else
            wget "$url" -O "$output" --no-check-certificate
        fi
    elif command -v curl >/dev/null 2>&1; then
        curl -fL --progress-bar "$url" -o "$output" -k
    else
        return 1
    fi
    local result=$?
    if [ "$result" -eq 0 ]; then
        echo -e "[${green}成功${plain}] 文件下载完成"
    fi
    return "$result"
}

# ===================== 端口校验/随机端口生成 =====================
is_valid_port() {
    local port="$1"
    [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1 ] && [ "$port" -le 65535 ]
}

is_port_available() {
    local port="$1"
    if command -v ss >/dev/null 2>&1; then
        ! ss -ltn "sport = :${port}" 2>/dev/null | grep -q ":${port}"
    elif command -v netstat >/dev/null 2>&1; then
        ! netstat -ltn 2>/dev/null | grep -q "[.:]${port}[[:space:]]"
    else
        return 0
    fi
}

generate_port() {
    local port
    for _ in {1..20}; do
        port=$((RANDOM % 45536 + 20000))
        if is_port_available "$port"; then
            echo "$port"
            return 0
        fi
    done
    echo "63521"
}

# ===================== 配置文件读写 =====================
getConfig() {
    local key="$1"
    local value=""
    if [ -f "$PATH_CONFIG" ]; then
        value=$(sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\(.*[^[:space:]]\)\([[:space:]]*\)$/\1/p" "$PATH_CONFIG")
    fi
    echo "$value"
}

setConfig() {
    if [ ! -f "$PATH_CONFIG" ]; then
        echo -e "[${yellow}提示${plain}] 未检测到配置文件，自动创建"
        mkdir -p "$installPath"
        chmod 755 "$installPath"
        touch "$PATH_CONFIG"
        chmod 600 "$PATH_CONFIG"
        echo "START_PORT=11113" >> "$PATH_CONFIG"
        echo "ENABLE_WEB_TLS=0" >> "$PATH_CONFIG"
        echo "ENABLE_WEB_UI=1" >> "$PATH_CONFIG"
    fi
    if grep -q "^$1=" "$PATH_CONFIG"; then
        sed -i "s/^$1=.*/$1=$2/" "$PATH_CONFIG"
        echo -e "[${green}配置${plain}] 已更新参数 $1=$2"
    else
        echo "$1=$2" >> "$PATH_CONFIG"
        echo -e "[${green}配置${plain}] 新增参数 $1=$2"
    fi
}

# ===================== 系统TCP/文件句柄优化 =====================
cleanup_global_network_optimization() {
    local keys=(
        fs.file-max fs.inotify.max_user_instances
        net.ipv4.tcp_congestion_control net.core.default_qdisc
        net.ipv4.tcp_fin_timeout net.ipv4.tcp_fastopen net.ipv4.tcp_fastopen_blackhole_timeout_sec
        net.ipv4.tcp_max_orphans net.ipv4.tcp_tw_reuse net.ipv4.ip_local_port_range
        net.ipv4.tcp_rmem net.ipv4.tcp_wmem net.ipv4.tcp_no_metrics_save
        net.ipv4.tcp_mtu_probing net.ipv4.tcp_notsent_lowat
        net.ipv4.tcp_syn_retries net.ipv4.tcp_synack_retries
        net.ipv4.tcp_keepalive_time net.ipv4.tcp_keepalive_intvl net.ipv4.tcp_keepalive_probes
        net.core.somaxconn net.core.rmem_max net.core.wmem_max
        net.core.rmem_default net.core.wmem_default
        net.core.netdev_max_backlog net.core.netdev_budget
        net.ipv4.tcp_max_tw_buckets net.ipv4.tcp_max_syn_backlog net.ipv4.tcp_slow_start_after_idle
        vm.swappiness vm.dirty_ratio vm.dirty_background_ratio
    )
    local files=("/etc/sysctl.conf")
    local f
    local key
    sed -i '/ulimit -SHn/d' /etc/profile 2>/dev/null || true
    touch /etc/sysctl.conf
    if [ -d /etc/sysctl.d ]; then
        while IFS= read -r f; do
            [ -f "$f" ] && files+=("$f")
        done < <(find /etc/sysctl.d -maxdepth 1 -name "*.conf" 2>/dev/null)
    fi
    for f in "${files[@]}"; do
        [ -f "$f" ] || continue
        sed -i '/^# === ${SYSCTL_TAG} network optimization begin ===/,/^# === ${SYSCTL_TAG} network optimization end ===/d' "$f"
        for key in "${keys[@]}"; do
            sed -i "/^[[:space:]]*${key}[[:space:]]*=/d" "$f"
        done
    done
    rm -f "/etc/sysctl.d/99-${SYSCTL_TAG}-optimize.conf" /etc/sysctl.d/99-tcpmux-optimize.conf 2>/dev/null || true
}

sysctl_key_path() {
    local key="$1"
    echo "/proc/sys/${key//./\/}"
}

apply_sysctl_setting() {
    local key="$1"
    local value="$2"
    local output_file="$3"
    local available
    [ -e "$(sysctl_key_path "$key")" ] || return 1
    if [ "$key" = "net.ipv4.tcp_congestion_control" ]; then
        available=$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)
        [[ "$available" == *"$value"* ]] || return 1
    fi
    if sysctl -w "${key}=${value}" >/dev/null 2>&1; then
        echo "${key} = ${value}" >> "$output_file"
        return 0
    fi
    return 1
}

apply_global_network_optimization() {
    local sysctl_file="/etc/sysctl.conf"
    local applied_count=0
    if ! command -v sysctl >/dev/null 2>&1; then
        echo -e "[${red}错误${plain}] 未找到sysctl，无法优化网络参数"
        return 1
    fi
    cleanup_global_network_optimization
    {
        echo ""
        echo "# === ${SYSCTL_TAG} network optimization begin ==="
        echo "# Generated by hhminer.sh 连接数优化"
        echo "# 文件句柄与TCP队列优化"
    } >> "$sysctl_file"
    apply_sysctl_setting fs.file-max 1048576 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting fs.inotify.max_user_instances 8192 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.default_qdisc fq "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_congestion_control bbr "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_fastopen 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_fastopen_blackhole_timeout_sec 0 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_fin_timeout 15 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_max_orphans 262144 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_tw_reuse 1 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_max_tw_buckets 2000000 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_max_syn_backlog 65535 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_slow_start_after_idle 0 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_no_metrics_save 1 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_mtu_probing 1 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_notsent_lowat 16384 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_syn_retries 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_synack_retries 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_keepalive_time 600 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_keepalive_intvl 30 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_keepalive_probes 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.ip_local_port_range "10000 65535" "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_rmem "4096 87380 16777216" "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_wmem "4096 65536 16777216" "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.somaxconn 65535 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.rmem_max 16777216 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.wmem_max 16777216 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.rmem_default 2097152 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.wmem_default 2097152 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.netdev_max_backlog 50000 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.netdev_budget 600 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting vm.swappiness 10 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting vm.dirty_ratio 10 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting vm.dirty_background_ratio 5 "$sysctl_file" && applied_count=$((applied_count + 1))
    echo "# === ${SYSCTL_TAG} network optimization end ===" >> "$sysctl_file"
    mkdir -p /etc/security/limits.d
    cat > "/etc/security/limits.d/99-${SYSCTL_TAG}.conf" <<'EOF'
* soft nofile 1048576
* hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576
EOF
    if is_systemd_available; then
        mkdir -p /etc/systemd/system.conf.d /etc/systemd/user.conf.d
        cat > "/etc/systemd/system.conf.d/99-${SYSCTL_TAG}-limits.conf" <<'EOF'
[Manager]
DefaultLimitNOFILE=1048576
EOF
        cat > "/etc/systemd/user.conf.d/99-${SYSCTL_TAG}-limits.conf" <<'EOF'
[Manager]
DefaultLimitNOFILE=1048576
EOF
        systemctl daemon-reload
    fi
    sysctl -p "$sysctl_file" >/dev/null 2>&1 || true
    echo -e "[${green}优化${plain}] 全局网络/文件句柄优化完成，修改项:${applied_count}，重启服务器生效"
}

# ===================== 防火墙关闭 =====================
disable_firewall() {
    local os_name="${OS_ID:-unknown}"
    echo -e "[${yellow}操作${plain}] 尝试关闭系统防火墙"
    if [ "$os_name" == "ubuntu" ] && command -v ufw >/dev/null 2>&1; then
        ufw disable
        echo -e "[${green}成功${plain}] Ubuntu ufw防火墙已关闭"
    elif [[ "$os_name" =~ ^(centos|rhel|rocky|almalinux|fedora)$ ]] && is_systemd_available; then
        systemctl stop firewalld
        systemctl disable firewalld
        echo -e "[${green}成功${plain}] CentOS firewalld防火墙已关闭"
    else
        echo -e "[${yellow}提示${plain}] 未知系统，自动关闭防火墙失败，请手动放行端口"
    fi
}

# ===================== 进程启停等待工具 =====================
check_process() {
    pgrep -x "$serviceName" >/dev/null 2>&1
}

is_fast_process_wait_supported() {
    if [ -n "$PROCESS_WAIT_INTERVAL_SUPPORTED" ]; then
        [ "$PROCESS_WAIT_INTERVAL_SUPPORTED" = "1" ]
        return
    fi
    if sleep "$PROCESS_WAIT_INTERVAL" 2>/dev/null; then
        PROCESS_WAIT_INTERVAL_SUPPORTED="1"
        return 0
    fi
    PROCESS_WAIT_INTERVAL_SUPPORTED="0"
    return 1
}

wait_for_process_started() {
    local timeout="${2:-10}"
    local interval="1"
    local max_attempts="$timeout"
    local attempts=0
    if check_process; then
        return 0
    fi
    if is_fast_process_wait_supported; then
        interval="$PROCESS_WAIT_INTERVAL"
        max_attempts=$((timeout * PROCESS_WAIT_STEPS_PER_SECOND))
    fi
    while [ "$attempts" -lt "$max_attempts" ]; do
        if check_process; then
            return 0
        fi
        sleep "$interval"
        attempts=$((attempts + 1))
    done
    return 1
}

wait_for_process_stopped() {
    local timeout="${2:-10}"
    local interval="1"
    local max_attempts="$timeout"
    local attempts=0
    if ! check_process; then
        return 0
    fi
    if is_fast_process_wait_supported; then
        interval="$PROCESS_WAIT_INTERVAL"
        max_attempts=$((timeout * PROCESS_WAIT_STEPS_PER_SECOND))
    fi
    while [ "$attempts" -lt "$max_attempts" ]; do
        if ! check_process; then
            return 0
        fi
        sleep "$interval"
        attempts=$((attempts + 1))
    done
    return 1
}

kill_process() {
    local pids=($(pgrep -x "$serviceName"))
    if [ ${#pids[@]} -eq 0 ]; then
        echo -e "[${yellow}提示${plain}] 未检测到$serviceName进程"
        return 1
    fi
    for pid in "${pids[@]}"; do
        echo -e "[${yellow}停止${plain}] 终止进程PID:$pid"
        kill -TERM "$pid"
    done
    if wait_for_process_stopped 10; then
        echo -e "[${green}成功${plain}] 进程全部终止"
    else
        echo -e "[${red}错误${plain}] 进程停止超时，强制kill"
        for pid in "${pids[@]}"; do kill -9 $pid; done
    fi
}

# ===================== 运行目录初始化 =====================
ensure_runtime_files() {
    mkdir -p "$installPath"
    chmod 755 "$installPath"
    [ -f "$PATH_NOHUP" ] || touch "$PATH_NOHUP"
    [ -f "$PATH_ERR" ] || touch "$PATH_ERR"
    chmod 640 "$PATH_NOHUP" "$PATH_ERR"
}

# ===================== systemd服务创建/删除（原版增强） =====================
create_service() {
    ensure_runtime_files
    # 新版systemd服务文件（融合install.sh日志输出）
    cat > /lib/systemd/system/${serviceName}.service << EOT
[Unit]
Description=${APP_NAME}
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
WorkingDirectory=${installPath}
Environment=HOME=${installPath}
ExecStart=/bin/sh -c 'exec "${installPath}/${serviceName}" >> "${PATH_NOHUP}" 2>> "${PATH_ERR}"' sh
SyslogIdentifier=${serviceName}
StandardOutput=syslog
Restart=always
RestartSec=3
TimeoutSec=300
LimitCORE=infinity
LimitNOFILE=1048576
LimitNPROC=655360
[Install]
WantedBy=multi-user.target
EOT
    # rsyslog日志（原版保留）
    touch /var/log/${serviceName}.log
    touch /var/log/hhminer.log
    cat > /etc/rsyslog.d/${serviceName}.conf << EOT
if \$programname == '${serviceName}' then /var/log/${serviceName}.log
& stop
EOT
    systemctl restart rsyslog > /dev/null 2>&1 &
    systemctl daemon-reload
    systemctl enable ${serviceName}
}

remove_service_file() {
    if is_systemd_available; then
        systemctl disable --now "${serviceName}.service" >/dev/null 2>&1
        rm -f -- "/lib/systemd/system/${serviceName}.service"
        rm -f -- "/usr/lib/systemd/system/${serviceName}.service"
        rm -f -- "/etc/rsyslog.d/${serviceName}.conf"
        systemctl restart rsyslog > /dev/null 2>&1 &
        systemctl daemon-reload
    else
        sed -i "/${serviceName}/d" /etc/rc.local 2>/dev/null || true
    fi
}

# ===================== 启停/重启核心 =====================
start() {
    echo -e "[${yellow}操作${plain}] 启动$serviceName代理程序"
    check_process
    if [ $? -eq 0 ]; then
        echo -e "[${yellow}提示${plain}] 程序已在运行，无需重复启动"
        return
    fi
    ensure_runtime_files
    create_service
    systemctl start "${serviceName}.service"
    if wait_for_process_started 10; then
        clear
        port=$(getConfig "START_PORT")
        https=$(getConfig "ENABLE_WEB_TLS")
        web_ui=$(getConfig "ENABLE_WEB_UI")
        ip=$(get_ip)
        echo ""
        echo -e "|----------------------------------------------------------------|"
        echo -e "           ${green}程序启动成功${plain}, 版本: ${bold}${blue}${VERSION}${plain}          "
        echo -e ""
        if [ "$web_ui" = "1" ];then
            if [ "$https" = 0 ];then
                echo -e "WEB访问地址:     ${green}http://${ip}:${port}${plain}"
                echo -e "[${yellow}提示${plain}] 当前HTTP模式，请勿用https访问"
            else
                echo -e "WEB访问地址:     ${green}https://${ip}:${port}${plain}"
                echo -e "[${yellow}提示${plain}] 当前HTTPS模式，请勿用http访问"
            fi
            echo -e "默认账号: admin"
            echo -e "默认密码: 1122345"
            echo -e ""
            echo -e "[${yellow}安全提示${plain}] 服务器/服务商防火墙务必放行${port}端口，登录后修改默认密码与端口"
        else
            echo -e "[${yellow}提示${plain}] WEB面板已关闭，仅可通过hhminerctl CLI工具管理"
        fi
        echo "|----------------------------------------------------------------|"
    else
        echo -e "[${red}错误${plain}] 程序启动失败，请查看错误日志(菜单10)"
    fi
}

stop() {
    echo -e "[${yellow}操作${plain}] 停止$serviceName进程"
    if is_systemd_available && [ -f "/lib/systemd/system/${serviceName}.service" ]; then
        systemctl stop "${serviceName}.service"
    fi
    if check_process; then
        kill_process
    else
        echo -e "[${yellow}提示${plain}] 未检测到运行中的$serviceName进程"
    fi
}

restart() {
    stop
    sleep 1
    start
}

# ===================== 端口修改、HTTPS、WEB面板开关 =====================
set_port() {
    read -p "请输入新WEB端口号: " choose
    if ! is_valid_port "$choose"; then
        echo -e "[${red}错误${plain}] 端口非法，范围1-65535"
        return 1
    fi
    if ! is_port_available "$choose"; then
        echo -e "[${red}错误${plain}] 端口已被占用，请更换其他端口"
        return 1
    fi
    setConfig START_PORT "$choose"
    restart
}

set_https() {
    echo "是否开启HTTPS后台访问"
    echo "1. 关闭HTTP模式"
    echo "2. 开启HTTPS模式"
    read -p "请选择 [1-2]: " choose
    case $choose in
    1)
        setConfig ENABLE_WEB_TLS 0
        ;;
    2)
        setConfig ENABLE_WEB_TLS 1
        ;;
    *)
        echo -e "[${yellow}提示${plain}] 输入错误，默认开启HTTPS"
        setConfig ENABLE_WEB_TLS 1
        ;;
    esac
    restart
}

set_web_ui() {
    local enabled="$1"
    echo -e "[${yellow}警告${plain}] 修改WEB面板开关会重启程序"
    echo "1. 确认继续并重启程序"
    echo "2. 取消操作"
    read -p "请选择: " choose
    case "$choose" in
    1)
        ;;
    2)
        echo -e "[${yellow}提示${plain}] 已取消操作"
        return 1
        ;;
    *)
        echo -e "[${red}错误${plain}] 输入无效，取消操作"
        return 1
        ;;
    esac
    stop
    setConfig ENABLE_WEB_UI "$enabled"
    start
    if [ "$enabled" = "1" ]; then
        echo -e "[${green}成功${plain}] WEB网页面板已开启"
    else
        echo -e "[${green}成功${plain}] WEB网页面板已关闭，仅CLI可用"
    fi
}

enable_web_ui() { set_web_ui 1; }
disable_web_ui() { set_web_ui 0; }

# ===================== 密码重置、日志管理 =====================
resetpass() {
    stop
    echo -e "[${yellow}操作${plain}] 删除数据库文件重置账号密码"
    rm -rf "${PATH_D_1}" "${PATH_D_2}" "${PATH_D_3}"
    start
    echo -e "[${green}完成${plain}] 密码重置成功，默认账号admin / 1122345"
}

clearlog() {
    echo -e "[${yellow}操作${plain}] 清空运行日志与错误日志"
    : > "$PATH_NOHUP" 2>/dev/null || touch "$PATH_NOHUP"
    : > "$PATH_ERR" 2>/dev/null || touch "$PATH_ERR"
    chmod 640 "$PATH_NOHUP" "$PATH_ERR" 2>/dev/null || true
    echo -e "[${green}成功${plain}] 日志清理完成"
}

view_runtime_log() {
    echo -e "[${yellow}提示${plain}] 按Ctrl+C退出日志查看"
    tail -f "$PATH_NOHUP"
}

view_error_log() {
    echo -e "[${yellow}提示${plain}] 按Ctrl+C退出日志查看"
    tail -f "$PATH_ERR"
}

view_systemd_log() {
    if ! command -v journalctl >/dev/null 2>&1; then
        echo -e "[${red}错误${plain}] 当前系统不支持journalctl"
        return 1
    fi
    echo -e "[${yellow}提示${plain}] 查看systemd服务日志，Ctrl+C退出"
    journalctl -u "${serviceName}.service" -n 100 -f
}

lookport() {
    port=$(getConfig "START_PORT")
    echo -e "[${green}当前WEB端口${plain}]: $port"
}

# ===================== 运行状态面板 =====================
show_runtime_status() {
    get_service_status() {
        local active_state
        if ! is_systemd_available; then
            service_status_color="$yellow"
            service_status_text="systemd不可用"
            return
        fi
        active_state=$(systemctl is-active "${serviceName}.service" 2>/dev/null)
        case "$active_state" in
        active)
            service_status_color="$green"
            service_status_text="运行中"
            ;;
        inactive|unknown|"")
            service_status_color="$yellow"
            service_status_text="已停止"
            ;;
        *)
            service_status_color="$red"
            service_status_text="异常"
            ;;
        esac
    }
    get_service_status
    if check_process; then
        process_status="运行中"
        process_pids=$(pgrep -x "$serviceName" 2>/dev/null | awk 'BEGIN{s=""} {s=s (s==""?"":",") $1} END{print s}')
    else
        process_status="未启动"
        process_pids="-"
    fi
    if is_systemd_available; then
        if systemctl is-enabled "${serviceName}.service" >/dev/null 2>&1; then
            autostart_status="是"
        else
            autostart_status="否"
        fi
        [ -f "/lib/systemd/system/${serviceName}.service" ] && service_file_status="存在" || service_file_status="缺失"
    else
        autostart_status="未知(sysv)"
        service_file_status="无systemd"
    fi
    web_ui=$(getConfig "ENABLE_WEB_UI")
    [ "$web_ui" = "0" ] && web_ui="关闭" || web_ui="开启"
    web_tls=$(getConfig "ENABLE_WEB_TLS")
    [ "$web_tls" = "1" ] && web_mode="HTTPS" || web_mode="HTTP"
    web_port=$(getConfig "START_PORT")
    [ -z "$web_port" ] && web_port="未配置"
    nofile_limit="$(ulimit -Sn 2>/dev/null || true)/$(ulimit -Hn 2>/dev/null || true)"
    fs_file_max=$(sed -n '1p' /proc/sys/fs/file-max 2>/dev/null || echo "未知")
    echo ""
    echo -e "${bold}${blue}================ hhMiner 运行状态面板 =================${plain}"
    echo -e "${bold}基础信息${plain}"
    echo -e "程序名称: ${APP_NAME}"
    echo -e "脚本版本: ${VERSION}"
    echo -e "系统名称: ${OS_NAME}"
    echo -e "初始化系统: ${INIT_SYSTEM}"
    echo ""
    echo -e "${bold}运行状态${plain}"
    echo -e "服务名称: ${serviceName}"
    echo -e "服务文件: ${service_file_status}"
    echo -e "服务状态: ${service_status_color}${service_status_text}${plain}"
    echo -e "进程状态: ${process_status}"
    echo -e "进程PID: ${process_pids}"
    echo -e "开机自启: ${autostart_status}"
    echo ""
    echo -e "${bold}WEB访问配置${plain}"
    echo -e "WEB面板: ${web_ui}"
    echo -e "访问协议: ${web_mode}"
    echo -e "WEB端口: ${web_port}"
    echo ""
    echo -e "${bold}文件路径${plain}"
    echo -e "安装目录: ${installPath}"
    echo -e "主程序: ${installPath}/${serviceName}"
    echo -e "配置文件: ${PATH_CONFIG}"
    echo -e "运行日志: ${PATH_NOHUP}"
    echo -e "错误日志: ${PATH_ERR}"
    echo ""
    echo -e "${bold}系统资源限制${plain}"
    echo -e "文件句柄限制(软/硬): ${nofile_limit}"
    echo -e "系统全局file-max: ${fs_file_max}"
    echo -e "${bold}${blue}=========================================================${plain}"
}

# ===================== CLI命令行工具安装/卸载 =====================
ensure_cli_dependencies() {
    local missing=""
    local cmd
    for cmd in cat grep readlink; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            missing="${missing} ${cmd}"
        fi
    done
    if [ -n "$missing" ]; then
        echo -e "[${red}错误${plain}] CLI依赖缺失:$missing"
        return 1
    fi
}

is_hhminer_installed() {
    [ -x "${installPath}/${serviceName}" ]
}

is_cli_managed_command() {
    [ -L "$CLI_LINK_PATH" ] && readlink "$CLI_LINK_PATH" | grep -q "$PATH_CLI" || grep -q "$CLI_LAUNCHER_MARKER" "$CLI_LINK_PATH" 2>/dev/null
}

is_cli_installed() {
    [ -x "$PATH_CLI" ] && is_cli_managed_command
}

check_cli_command_conflict() {
    local existing_command
    existing_command=$(command -v "$CLI_COMMAND_NAME" 2>/dev/null || true)
    if [ -n "$existing_command" ]; then
        if [ "$existing_command" = "$CLI_LINK_PATH" ] && is_cli_managed_command; then
            return 0
        fi
        echo -e "[${red}错误${plain}] $CLI_COMMAND_NAME 命令已存在，非本脚本管理，冲突"
        return 1
    fi
    if [ -e "$CLI_LINK_PATH" ] || [ -L "$CLI_LINK_PATH" ]; then
        if is_cli_managed_command; then
            return 0
        fi
        echo -e "[${red}错误${plain}] $CLI_LINK_PATH 文件存在，冲突"
        return 1
    fi
}

create_cli_launcher() {
    mkdir -p /usr/local/bin
    [ -L "$CLI_LINK_PATH" ] && rm -f -- "$CLI_LINK_PATH"
    cat > "$CLI_LINK_PATH" <<EOF
#!/bin/sh
# ${CLI_LAUNCHER_MARKER}
APP_DIR="$installPath"
APP_EXEC="$serviceName"
CLI_EXEC="$CLI_EXEC_NAME"
SERVICE_NAME="$serviceName"
APP_PATH="\${APP_DIR}/\${APP_EXEC}"
CLI_PATH="\${APP_DIR}/\${CLI_EXEC}"
CONFIG_FILE="\${APP_DIR}/$CONFIG_FILE_NAME"
NOHUP_FILE="\${APP_DIR}/nohup.out"
ERR_FILE="\${APP_DIR}/err.log"
SERVICE_FILE="/lib/systemd/system/\${SERVICE_NAME}.service"
show_usage() {
    echo "用法: hhminerctl [start|stop|restart|help]"
}
require_root() {
    if [ "\$(id -u)" != "0" ]; then
        echo "请使用root用户执行"
        exit 1
    fi
}
is_systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}
is_running() {
    pgrep -x "\$APP_EXEC" >/dev/null 2>&1
}
ensure_app_exists() {
    if [ ! -x "\$APP_PATH" ]; then
        echo "未安装hhminer，请先执行脚本安装"
        return 1
    fi
}
open_cli() {
    if [ ! -x "\$CLI_PATH" ]; then
        echo "CLI工具未安装，请通过脚本菜单安装"
        exit 1
    fi
    web_ui=\$(sed -n 's/^[[:space:]]*ENABLE_WEB_UI[[:space:]]*=[[:space:]]*\([^[:space:]]*\).*$/\1/p' "\$CONFIG_FILE" 2>/dev/null | tail -n 1)
    if [ "\$web_ui" != "0" ]; then
        echo "CLI工具仅在WEB面板关闭后可用，请先关闭WEB访问"
        exit 1
    fi
    cd "\$APP_DIR" || exit 1
    exec "\$CLI_PATH"
}
start_app() {
    require_root
    ensure_app_exists || return 1
    if is_running; then
        echo "hhminer已运行"
        return 0
    fi
    if is_systemd_available && [ -f "\$SERVICE_FILE" ]; then
        systemctl start "\${SERVICE_NAME}.service"
    else
        mkdir -p "\$APP_DIR"
        touch "\$NOHUP_FILE" "\$ERR_FILE"
        chmod 640 "\$NOHUP_FILE" "\$ERR_FILE" 2>/dev/null || true
        nohup "\$APP_PATH" >> "\$NOHUP_FILE" 2>> "\$ERR_FILE" &
    fi
    i=0
    while [ "\$i" -lt 10 ]; do
        if is_running; then
            echo "hhminer启动成功"
            return 0
        fi
        sleep 1
        i=\$((i + 1))
    done
    echo "hhminer启动失败"
    return 1
}
stop_app() {
    require_root
    was_running=0
    if is_running; then
        was_running=1
    fi
    if is_systemd_available && [ -f "\$SERVICE_FILE" ]; then
        systemctl stop "\${SERVICE_NAME}.service"
    fi
    if is_running; then
        pids=\$(pgrep -x "\$APP_EXEC")
        for pid in \$pids; do
            kill -TERM "\$pid"
        done
    fi
    i=0
    while [ "\$i" -lt 10 ]; do
        if ! is_running; then
            if [ "\$was_running" = "1" ]; then
                echo "hhminer已停止"
            else
                echo "hhminer未运行"
            fi
            return 0
        fi
        sleep 1
        i=\$((i + 1))
    done
    echo "停止超时"
    return 1
}
restart_app() {
    stop_app || return 1
    start_app
}
if [ "\$#" -eq 0 ]; then
    open_cli
fi
case "\$1" in
start) start_app ;;
stop) stop_app ;;
restart) restart_app ;;
help|--help|-h) show_usage ;;
*) echo "未知命令: \$1"; show_usage; exit 1 ;;
esac
EOF
    chmod 755 "$CLI_LINK_PATH"
}

install_cli() {
    echo -e "[${yellow}CLI安装${plain}] 开始安装hhminerctl命令行工具"
    ensure_cli_dependencies || return 1
    if ! is_hhminer_installed; then
        echo -e "[${red}错误${plain}] 请先完成hhminer主程序安装"
        return 1
    fi
    if ! is_cli_installed; then
        check_cli_command_conflict || return 1
    fi
    echo -e "[${red}警告${plain}] 安装CLI会自动关闭WEB网页面板，网页将无法访问"
    echo "1. 确认继续安装CLI"
    echo "2. 取消"
    read -p "请选择: " choose
    case "$choose" in
    1) ;;
    2) echo -e "[${yellow}提示${plain}] CLI安装已取消"; return 1 ;;
    *) echo -e "[${red}错误${plain}] 输入无效，取消"; return 1 ;;
    esac
    if ! is_cli_installed; then
        rm -f -- "$PATH_CLI_TMP"
        download_file "${DOWNLOAD_HOST}/${CLI_EXEC_NAME}" "$PATH_CLI_TMP"
        if [ $? -ne 0 ]; then
            echo -e "[${red}错误${plain}] CLI工具下载失败"
            return 1
        fi
        chmod 755 "$PATH_CLI_TMP"
        mv -f "$PATH_CLI_TMP" "$PATH_CLI"
    fi
    create_cli_launcher
    stop
    setConfig ENABLE_WEB_UI 0
    start
    echo ""
    echo -e "${green}================ CLI工具安装完成 =================${plain}"
    echo -e "CLI程序路径: ${PATH_CLI}"
    echo -e "全局命令: ${CLI_COMMAND_NAME}"
    echo -e "使用方式: hhminerctl start/stop/restart/help"
    echo -e "${green}====================================================${plain}"
    "$CLI_LINK_PATH"
}

uninstall_cli() {
    ensure_cli_dependencies || return 1
    if [ ! -e "$PATH_CLI" ] && ! is_cli_managed_command; then
        echo -e "[${yellow}提示${plain}] CLI工具未安装"
        return
    fi
    read -p "输入YES确认卸载CLI工具: " confirm
    if [ "$confirm" != "YES" ]; then
        echo -e "[${yellow}提示${plain}] 卸载已取消"
        return
    fi
    if [ -e "$CLI_LINK_PATH" ] && is_cli_managed_command; then
        rm -f -- "$CLI_LINK_PATH"
    fi
    rm -f -- "$PATH_CLI" "$PATH_CLI_TMP"
    echo -e "[${green}成功${plain}] CLI工具卸载完成"
}

# ===================== 原版安装/更新/卸载逻辑（增强） =====================
install_hhminer() {
    check_os
    detect_system
    check_dependencies
    # 安装wget
    case $os in
        'ubuntu'|'debian')
            apt-get -y update >/dev/null 2>&1
            apt-get -y install wget git >/dev/null 2>&1
            ;;
        'centos')
            yum install -y wget git >/dev/null 2>&1
            ;;
    esac
    # 检测运行中程序，停止后安装
    if check_process; then
        echo -e "[${yellow}提示${plain}] 检测到hhminer正在运行，必须停止才能更新/重装"
        echo "1. 停止程序并继续安装"
        echo "2. 取消安装"
        read -p "请选择: " choose
        case $choose in
        1) stop ;;
        2) echo -e "[${yellow}提示${plain}] 安装取消"; return ;;
        *) echo -e "[${red}错误${plain}] 输入无效，取消安装"; return ;;
        esac
    fi
    disable_firewall
    apply_global_network_optimization
    # 清理更新目录
    if [ -d ${updatePath} ]; then
        rm -rf ${updatePath}
    fi
    mkdir -p ${updatePath}
    cd ${updatePath}
    # 下载主程序
    wget --no-check-certificate https://raw.githubusercontent.com/735840086/hhminer/main/hhminer -O hhminer
    if [ $? -ne 0 ]; then
        echo -e "[${red}错误${plain}] 主程序下载失败"
        exit -1;
    fi
    chmod +x hhminer
    # 下载版本文件
    wget --no-check-certificate https://raw.githubusercontent.com/735840086/hhminer/main/version -O version
    if [ $? -ne 0 ]; then
        echo -e "[${red}错误${plain}] version文件下载失败"
        exit -1;
    fi
    # 备份旧程序
    if [ -f "${installPath}/hhminer.bak" ]; then
        rm -rf "${installPath}/hhminer.bak"
        rm -rf "${installPath}/version.bak"
    fi
    if [ -f "${installPath}/hhminer" ]; then
        mv "${installPath}/hhminer" "${installPath}/hhminer.bak"
        mv "${installPath}/version" "${installPath}/version.bak"
    fi
    # 移动新文件到安装目录
    mv "${updatePath}/hhminer" "${installPath}/hhminer"
    mv "${updatePath}/version" "${installPath}/version"
    # 自动生成随机端口（无配置时）
    if [ ! -f "$PATH_CONFIG" ]; then
        default_port=$(generate_port)
        setConfig START_PORT "$default_port"
    fi
    # 创建服务并启动
    create_service
    start
}

update_hhminer() {
    if [ -d ${updatePath} ]; then
        rm -rf ${updatePath}
    fi
    mkdir -p ${updatePath}
    cd ${updatePath}
    wget --no-check-certificate https://raw.githubusercontent.com/735840086/hhminer/main/version -O version
    if [ $? -ne 0 ]; then
        echo -e "[${red}错误${plain}] 获取版本文件失败"
        exit -1;
    fi
    newVersion=$(cat ${updatePath}/version)
    oldVerion=$(cat ${installPath}/version 2>/dev/null || echo "0")
    if [ "${newVersion}" == "${oldVerion}" ]; then
        echo -e "[${green}提示${plain}] 当前已是最新版本，无需更新"
        exit 0
    fi
    echo -e "[${yellow}更新${plain}] 检测到新版本:$newVersion，开始更新"
    install_hhminer
}

uninstall_hhminer() {
    read -p "输入YES确认完全卸载hhminer（删除程序、配置、日志、服务）: " confirm
    if [ "$confirm" != "YES" ]; then
        echo -e "[${yellow}提示${plain}] 卸载操作已取消"
        return
    fi
    stop
    remove_service_file
    uninstall_cli
    rm -rf ${installPath}
    echo -e "[${green}成功${plain}] hhminer全部文件、服务、CLI工具已卸载完毕"
}

# ===================== 主菜单 =====================
show_menu() {
    clear
    get_service_status() {
        local active_state
        if ! is_systemd_available; then
            service_status_color="$yellow"
            service_status_text="systemd不可用"
            return
        fi
        active_state=$(systemctl is-active "${serviceName}.service" 2>/dev/null)
        case "$active_state" in
        active)
            service_status_color="$green"
            service_status_text="运行中"
            ;;
        inactive|unknown|"")
            service_status_color="$yellow"
            service_status_text="已停止"
            ;;
        *)
            service_status_color="$red"
            service_status_text="异常"
            ;;
        esac
    }
    get_service_status
    echo -e "${bold}${blue}+=============================================+${plain}"
    echo -e "${bold}  hhMiner Proxy 综合管理脚本 V${VERSION} ${plain}"
    echo -e "  ● 服务状态: ${service_status_color}${service_status_text}${plain}"
    echo -e "${bold}${blue}+=============================================+${plain}"
    echo -e "${bold}⭐部署更新${plain}"
    echo "  1. 安装/重装程序"
    echo "  2. 检测版本并更新程序"
    echo -e "${bold}⭐运行控制${plain}"
    echo "  3. 启动服务"
    echo "  4. 停止服务"
    echo "  5. 重启服务"
    echo -e "${bold}⭐WEB配置${plain}"
    echo "  6. 修改WEB访问端口"
    echo "  7. 开启/关闭HTTPS"
    echo "  8. 开启WEB网页面板"
    echo "  9. 关闭WEB网页面板"
    echo "  10. 查看当前WEB端口"
    echo -e "${bold}⭐系统优化${plain}"
    echo "  11. 解除系统TCP/文件句柄连接限制"
    echo -e "${bold}⭐日志管理${plain}"
    echo "  12. 查看systemd服务日志"
    echo "  13. 实时运行日志"
    echo "  14. 实时错误日志"
    echo "  15. 清空全部日志"
    echo -e "${bold}⭐维护工具${plain}"
    echo "  16. 重置后台登录密码"
    echo "  17. 查看完整运行状态面板"
    echo "  18. 卸载hhminer完整程序"
    echo -e "${bold}⭐CLI命令行工具${plain}"
    echo "  19. 安装全局CLI工具 hhminerctl"
    echo "  20. 卸载CLI工具"
    echo -e "${bold}${blue}+=============================================+${plain}"
    echo -e "${yellow}提示：连接限制修改后需重启服务器生效；防火墙放行WEB端口${plain}"
    echo -e "${bold}${blue}+=============================================+${plain}"
}

# ===================== 入口逻辑 =====================
# 必须root执行
if [ "$EUID" -ne 0 ]; then
    echo -e "[${red}错误${plain}] 请使用root权限执行本脚本"
    exit 1;
fi

# 主循环菜单
while true; do
    show_menu
    read -p "请输入操作序号: " opt
    case ${opt} in
    1) install_hhminer ;;
    2) update_hhminer ;;
    3) start ;;
    4) stop ;;
    5) restart ;;
    6) set_port ;;
    7) set_https ;;
    8) enable_web_ui ;;
    9) disable_web_ui ;;
    10) lookport ;;
    11) apply_global_network_optimization ;;
    12) view_systemd_log ;;
    13) view_runtime_log ;;
    14) view_error_log ;;
    15) clearlog ;;
    16) resetpass ;;
    17) show_runtime_status ;;
    18) uninstall_hhminer ;;
    19) install_cli ;;
    20) uninstall_cli ;;
    *)
        echo -e "[${red}错误${plain}] 输入序号无效，回车返回菜单"
        read
        ;;
    esac
    echo -e "\n${yellow}操作执行完成，按回车返回主菜单${plain}"
    read
done
